config/routes.rb
Autoillume::Application.routes.draw do

  resources :bios

  match 'admin/edit' => 'admins#edit', :as => :edit_current_admin
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions, only: [ :new, :create, :destroy]
  resources :admins, only: [ :edit, :update ]

  resources :replies
  resources :comments

  resources :preview_posts, only: [ :show, :edit, :update, :destroy ]
  resources :draft_posts, only: [ :index, :show ]
  resources :posts do
    resources :comments
  end
  resources :sections do
    collection do
      post 'sort'
    end
  end
  resources :photos

  resources :external_links do
    collection do
      post 'sort'
    end
  end

  get 'static/:permalink' => 'pages#show', as: :static
  get 'static/:permalink/edit' => 'pages#edit', as: :edit_static
  delete 'static/:permalink' => 'pages#destroy', as: :static, method: :delete
  resources :pages do
    collection do
      post 'sort'
    end
  end

  root :to => 'posts#index'

end

app/controllers/draft_posts_controller.rb
class DraftPostsController < ApplicationController
  before_filter  :admin_login_required
  # GET /draft_posts
  # GET /draft_posts.json
  def index
    @draft_posts = Post.drafts.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @draft_posts }
    end
  end

  # GET /draft_posts/1
  # GET /draft_posts/1.json
  def show
    @draft_post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @draft_post }
    end
  end

end

app/helpers/draft_posts_helper.rb
module DraftPostsHelper
end

app/views/draft_posts/index.html.haml
%header
  %h1 Listing Draft Posts

%table.draft_posts
  %tr
    %th Title
    %th Images
    %th Created
    %th
    %th
  - @draft_posts.each do |post|
    %tr
      %td= link_to post.title, draft_post_path(post), title: "Click here to reorder the images and text of this post.", class: "post_title_link" if post.title
      %td
        %ul
          - post.photo_sections.rank(:position).each do |photo_section|
            %li
              = image_tag photo_section.photo.image.thumb.url, title: "#{photo_section.photo.title ||= photo_section.photo.filename}", alt: "#{photo_section.photo.title ||= photo_section.photo.filname}" if photo_section.photo
      %td= post.created_at.strftime('%B %e, %Y')
      - if admin_logged_in?
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete
- if admin_logged_in?
  %br/
  = link_to 'New Post', new_post_path

app/views/draft_posts/show.html.haml
= render 'posts/post', object: @draft_post

/ #photo
/   = fields_for @photo do |f|
/     = f.file_field :image, :rel => photos_path

= photo_uploadify

%nav
  - if admin_logged_in?
    = link_to 'Edit', edit_post_path(@draft_post)
    \|
    = link_to 'Destroy', @draft_post, confirm: 'Are you sure?', method: :delete
    \|
  = link_to 'Back', draft_posts_path

- if @draft_post.state == "draft"
  %section.draft_post
    %header
      %h3 This post is a draft.
      = form_for @draft_post do |f|
        %fieldset
          %p.field
            = f.label :state, "Publish this post?"
            %br/
            = f.collection_select :state, @draft_post.state_transitions, :event, :human_to_name
          %p.field
            = f.label :published_at
            %br/
            = f.datetime_select :published_at
          .actions
            = f.submit 'Post'