config/routes.rb
Autoillume::Application.routes.draw do

  resources :bios

  match 'admin/edit' => 'admins#edit', :as => :edit_current_admin
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions, only: [ :new, :create, :destroy]
  resources :admins, only: [ :edit, :update ]

  resources :replies
  resources :comments

  resources :preview_posts, only: [ :show, :edit, :update, :destroy ]
  resources :draft_posts, only: [ :index, :show ]
  resources :posts do
    resources :comments
  end
  resources :sections do
    collection do
      post 'sort'
    end
  end
  resources :photos

  resources :external_links do
    collection do
      post 'sort'
    end
  end

  get 'static/:permalink' => 'pages#show', as: :static
  get 'static/:permalink/edit' => 'pages#edit', as: :edit_static
  delete 'static/:permalink' => 'pages#destroy', as: :static, method: :delete
  resources :pages do
    collection do
      post 'sort'
    end
  end

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :name, :email, :url, :body, :state

  belongs_to :post
  has_many  :replies, dependent: :destroy

  # States and Transitions with state_machine gem
  state_machine initial: :unapproved do
    event :approved do
      transition unapproved: :approved
    end
  end

  # Validations
  # email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  name_regex = /[a-zA-Z0-9_ ]/i
  url_regex = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
  # url_regex = \b((ftp|https?)://[-\w]+(\.\w[-\w]*)+ | (?i: [a-z0-9] (?:[-a-z0-9]*[a-z0-9])? \. )+(?-i: com\b | edu\b | biz\b | gov\b | in(?:t|fo)\b | mil\b | net\b | org\b | [a-z][a-z]\b ))( : \d+ )?)/[^.!,?;<>()\[\]{}\s\x7F-\xFF]*(?:[.!,?]+  [^.!,?;<>()\[\]{}\s\x7F-\xFF]+)*)?

  validates :name,           presence: true,
                                        length: { within: 3..60 },
                                        format: name_regex
  validates :email,           presence: true,
                                        length: { within: 5..120 },
                                        format: email_regex
  validates :url,                length: { within: 9..254, allow_blank: true },
                                        format: { with: url_regex, message: "Please provide a properly formatted URL."}
  validates :body,            presence: true,
                                        length: { within: 3..1024 }
  validates :post_id,        presence: true#, on: :create

  # Scopes
  default_scope order('created_at DESC') # test
  scope :unapproved, where(state: 'unapproved')
  scope :approved, where(state: 'approved')


end


# == Schema Information
#
# Table name: comments
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  url        :string(255)
#  body       :text
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  state      :string(255)
#

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter  :admin_login_required, only: [ :index, :edit, :update, :destroy ]
  # GET /comments
  # GET /comments.json
  def index
    @posts = Post.published.order('created_at ASC')

    @comments = Comment.all
    @approved_comments = Comment.approved.order('created_at ASC')
    @unapproved_comments = Comment.unapproved.order('created_at ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    find_post
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    find_post
    @comment = @post.comments.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    find_post
    @comment = @post.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    find_post
    @comment = @post.comments.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render controller: 'posts', action: "show" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    find_post
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    find_post
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_url(@post) }
      format.json { head :ok }
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
%article.comment
  %header.comment_name
    - if comment.url
      %h3= link_to comment.name, comment.url
    -else
      %h3= comment.name
  %section.comment_body
    :textile
      #{comment.body}

app/views/comments/_form.html.haml
- post ||= @post
- comment ||= @comment
= form_for [ post, comment ], validate: true, html: { id: "comment_form_#{ post.id }" } do |f|
  = f.error_messages
  %p.field
    = f.label :name, "name*"
    %br/
    = f.text_field :name, placeholder: "name*"
  %p.field
    = f.label :email, "email*"
    %br/
    = f.email_field :email, placeholder: "email address* (not shown)"
  %p.field
    = f.label :url, "URL"
    %br/
    = f.url_field :url, placeholder: "URL (share your website)"
  %p.field
    = f.label :body, "comments*"
    %br/
    = f.text_area :body, placeholder: "comments* (supports textile)"
    %br/
    * = required
  %p.actions
    = f.submit 'Post'

app/views/comments/create.js.erb
var el = $('<%= escape_javascript("#comment_form_#{@post.id}")%>');

<% if @comment.errors.any? %>
  // Create a list of errors
  var errors = $('<ul></ul>');

  <% @comment.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript( error ) %></li>');
  <% end %>
  // Display errors on form
  el.find('p.errors').html(errors).fadeIn(1000);

<% else %>
  // store element IDs in variables
  var commentsList = $('#<%= escape_javascript("comments_list") %>');
  var commentForm = $('#<%= escape_javascript("comment_form_#{@post.id}") %>');

  // render partial to display comment
  $(commentsList).append("<%= escape_javascript(render 'comments/show') %>");

  // update comment count

  var d = new Date();
  $(commentImage).attr("src", "/images/comment_blue.png?"+d.getTime());

  // Clear forms
  el.find('input:text,textarea').val('');
  el.find('.errors').empty();

<% end %>

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%header
  %h1 Listing comments

%section.approved
  %header
    %h2 Approved Comments
  - @posts.each do |post|
    %p= link_to post.title, post_path(post)
    %ul.comments_approved
      - post.comments.approved.each do |approved|
        %li.comment_approved
          = render 'comments/comment', comment: approved
          %nav
            = button_to "Destroy Comment", { action: 'destroy', controller: 'comments', id: approved.id, post_id: post.id }, confirm: "Are you sure?", method: :delete
    %ul.comments_unapproved
      - post.comments.unapproved.each do |unapproved|
        %li.comment_unapproved
          = render 'comments/comment', comment: unapproved
          %nav
            = form_for [ post, unapproved ], method: :put  do |f|
              = f.hidden_field :state, value: "approved"
              = f.submit "Approve Comment"
            = button_to "Destroy Comment", { action: 'destroy', controller: 'comments', id: unapproved.id, post_id: post.id }, confirm: "Are you sure?", method: :delete

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
= render 'comment', comment: @comment
%nav
  - if admin_logged_in?
    = link_to 'Edit', edit_comment_path(comment)
    |
  = link_to 'Back', comments_path