config/routes.rb
Autoillume::Application.routes.draw do

  resources :bios

  match 'admin/edit' => 'admins#edit', :as => :edit_current_admin
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions, only: [ :new, :create, :destroy]
  resources :admins, only: [ :edit, :update ]

  resources :replies
  resources :comments

  resources :preview_posts, only: [ :show, :edit, :update, :destroy ]
  resources :draft_posts, only: [ :index, :show ]
  resources :posts do
    resources :comments
  end
  resources :sections do
    collection do
      post 'sort'
    end
  end
  resources :photos

  resources :external_links do
    collection do
      post 'sort'
    end
  end

  get 'static/:permalink' => 'pages#show', as: :static
  get 'static/:permalink/edit' => 'pages#edit', as: :edit_static
  delete 'static/:permalink' => 'pages#destroy', as: :static, method: :delete
  resources :pages do
    collection do
      post 'sort'
    end
  end

  root :to => 'posts#index'

end

app/models/external_link.rb
class ExternalLink < ActiveRecord::Base
  include RankedModel #test for this
  ranks :link_order #test for this

  attr_accessible :title, :url, :description, :link_order

  url_regex = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix

  validates :title,                presence: true,
                                          uniqueness: true
  validates  :url,                 presence: true,
                                          uniqueness: true,
                                          format: { with: url_regex, message: "Your URL is not properly formatted." }
  validates :description,    length: { within: 3..254, allow_blank: true }
  validates :link_order,      presence: true
end

app/controllers/external_links_controller.rb
class ExternalLinksController < ApplicationController
  before_filter  :admin_login_required, except: [:show]
  # GET /external_links
  # GET /external_links.json
  def index
    @external_links = ExternalLink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @external_links }
    end
  end

  # GET /external_links/1
  # GET /external_links/1.json
  def show
    @external_link = ExternalLink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @external_link }
    end
  end

  # GET /external_links/new
  # GET /external_links/new.json
  def new
    @external_link = ExternalLink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @external_link }
    end
  end

  # GET /external_links/1/edit
  def edit
    @external_link = ExternalLink.find(params[:id])
  end

  # POST /external_links
  # POST /external_links.json
  def create
    @external_link = ExternalLink.new(params[:external_link])

    respond_to do |format|
      if @external_link.save
        format.html { redirect_to @external_link, notice: 'External link was successfully created.' }
        format.json { render json: @external_link, status: :created, location: @external_link }
      else
        format.html { render action: "new" }
        format.json { render json: @external_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /external_links/1
  # PUT /external_links/1.json
  def update
    @external_link = ExternalLink.find(params[:id])

    respond_to do |format|
      if @external_link.update_attributes(params[:external_link])
        format.html { redirect_to @external_link, notice: 'External link was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @external_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /external_links/1
  # DELETE /external_links/1.json
  def destroy
    @external_link = ExternalLink.find(params[:id])
    @external_link.destroy

    respond_to do |format|
      format.html { redirect_to external_links_url }
      format.json { head :ok }
    end
  end

  def sort
    params[:external_link].each_with_index do |id, index|
      ExternalLink.update_all(['link_order=?', index + 1], ['id=?', id])
    end
    render :nothing => true
  end
end

app/helpers/external_links_helper.rb
module ExternalLinksHelper
end

app/views/external_links/_form.html.haml
= form_for @external_link, validate: true do |f|
  -if @external_link.errors.any?
    #error_explanation
      %h2= "#{pluralize(@external_link.errors.count, "error")} prohibited this external_link from being saved:"
      %ul
        - @external_link.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/external_links/edit.html.haml
%h1 Editing external_link

= render 'form'

= link_to 'Show', @external_link
\|
= link_to 'Back', external_links_path

app/views/external_links/index.html.haml
%h1 Listing external links
%table#sortable_table
  %tr
    %th Title
    %th Url
    %th Description
    %th
    %th
    %th
  - @external_links.each do |link|
    %tr.page{ :id => "external_link_#{link.id}" }
      %td &dagger;drag&dagger;
      %td= link_to link.title, link.url, title: "View your #{link.title} page.", target: "_blank"
      %td= " . . . #{link.url}"
      %td= truncate(link.description, length: 32, omission: '...')
      - if admin_logged_in?
        %td= link_to 'Edit', edit_external_link_path(link)
        %td= link_to 'Destroy', external_link_path(link), confirm: 'Are you sure?', method: :delete
- if admin_logged_in?
  %br/
  = link_to 'New External link', new_external_link_path
  = links_sortable

app/views/external_links/new.html.haml
%h1 New external_link

= render 'form'

= link_to 'Back', external_links_path

app/views/external_links/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @external_link.title
%p
  %b Url:
  = @external_link.url
%p
  %b Link order:
  = @external_link.link_order
%p
  %b Description:
  = @external_link.description

= link_to 'Edit', edit_external_link_path(@external_link)
\|
= link_to 'Back', external_links_path