config/routes.rb
Autoillume::Application.routes.draw do

  resources :bios

  match 'admin/edit' => 'admins#edit', :as => :edit_current_admin
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions, only: [ :new, :create, :destroy]
  resources :admins, only: [ :edit, :update ]

  resources :replies
  resources :comments

  resources :preview_posts, only: [ :show, :edit, :update, :destroy ]
  resources :draft_posts, only: [ :index, :show ]
  resources :posts do
    resources :comments
  end
  resources :sections do
    collection do
      post 'sort'
    end
  end
  resources :photos

  resources :external_links do
    collection do
      post 'sort'
    end
  end

  get 'static/:permalink' => 'pages#show', as: :static
  get 'static/:permalink/edit' => 'pages#edit', as: :edit_static
  delete 'static/:permalink' => 'pages#destroy', as: :static, method: :delete
  resources :pages do
    collection do
      post 'sort'
    end
  end

  root :to => 'posts#index'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_debug.html.haml
/development debug information
#debug
  = debug(params)
  = debug(session)
/end development debug information

app/views/layouts/admin.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}
    = stylesheet_link_tag "admin"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)

  %body
    - if flash[:notice] || flash[:alert]
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
    %header.site_header
      .site-logo
        = link_to "(auto)illume", root_path, title: "(auto)illume -- home", class: "logo_link"
      %nav.top_nav

    #container
      %section#left_column
        - if show_title?
          %h1= yield(:title)
        %p.site_description
          Hi there, I’m Laura. This is a description of what goes on at Illume, and how, if you read this you can be awesome. This could go on for maybe a sentence more. Or maybe there could be one more sentence! { read more }
        - if @posts
          %section.search
            = search_form_for @q do |f|
              = f.text_field :title_or_sections_body_or_sections_photo_title_cont, size: 22, placeholder: 'search'
              = f.submit "X"
        %nav.left_nav
          %ul.nav_links.pages
            - @pages.rank(:page_order).each do |page|
              %li.nav_link.page= link_to page.title.to_s.upcase, static_path(page.permalink), title: page.title, description: truncate(page.content, length: 64, omission: '...')
            - if admin_logged_in?
              %li.nav_link.page= link_to "( add a static page )", new_page_path, title: "You can add new static pages to the menu here."
              %li.nav_link.page= link_to "( manage static page )", pages_path, title: "You can manage static pages here."
            %br
          %ul.nav_links.external_links
            - @external_links.each do |link|
              %li.nav_link.external_link= link_to link.title.to_s.upcase, link.url, title: link.title, description: truncate(link.description, length: 64, omission: '. . .'), target: '_blank'
            - if admin_logged_in?
              %li.nav_link.page= link_to "( add n external link)", new_external_link_path, title: "You can add new external links to the menu here."
              %li.nav_link.page= link_to "( manage external links )", external_links_path, title: "You can manage external links here."

          - if admin_logged_in?
            %ul.nav_links.admin_nav_links
              %li.nav_link= link_to "New Post", new_post_path
              %li.nav_link= link_to "#{pluralize Post.drafts.count, 'Draft Post'} ", draft_posts_path
              %li.nav_link= link_to "#{pluralize Comment.unapproved.count, 'Pending Comment'}", comments_path
              %li.nav_link= link_to "logout ( #{ current_admin.username if current_admin.username} )", logout_path
      %section#right_column
        = yield

    %footer
      %nav#footer

  - if Rails.env.development?
    = render "layouts/debug"